package org.cobbleutils.cobblecomputils.capture;

/** Generated by gen_mart.py: {merchant, trigger, item count, icon}. */
final class MartData {
    private MartData() {}
    static final String[][] SHOPS = {
        {"Apricorn Salesman", "32001", "7", "cobblemon:black_apricorn"},
        {"Arborist", "32002", "40", "cobblemon:red_apricorn_seed"},
        {"Battle Master", "32003", "15", "cobblemon:leftovers"},
        {"Battle Specialist", "32004", "18", "cobblemon:black_belt"},
        {"Battle Strategist", "32005", "49", "cobblemon:toxic_orb"},
        {"Berry Trader", "32006", "8", "cobblemon:razz_berry"},
        {"Bundler", "32007", "1", "minecraft:bundle"},
        {"Chef", "32008", "14", "cobblemon:rage_candy_bar"},
        {"Color Specialist", "32009", "18", "minecraft:black_dye"},
        {"Disc Merchant", "32010", "10", "minecraft:music_disc_blocks"},
        {"Evolution Specialist", "32011", "37", "cobblemon:deep_sea_scale"},
        {"Exotic Provisions Seller", "32012", "5", "minecraft:pufferfish"},
        {"Experience Trainer", "32013", "7", "cobblemon:exp_candy_xs"},
        {"Fishing Gear Keeper", "32014", "5", "minecraft:fishing_rod"},
        {"Floral Specialist", "32015", "12", "cobblemon:hearty_grains"},
        {"Food Merchant", "32016", "13", "minecraft:carrot"},
        {"Gardening Specialist", "32017", "9", "cobblemon:mulch_base"},
        {"Master of Stones", "32018", "28", "cobblemon:fire_stone"},
        {"Meat Merchant", "32019", "6", "minecraft:mutton"},
        {"Milkman", "32020", "2", "cobblemon:moomoo_milk"},
        {"Mint Vendor", "32021", "5", "cobblemon:pink_mint_leaf"},
        {"Mochi Merchant", "32022", "7", "cobblemon:health_mochi"},
        {"Naturalist", "32023", "17", "cobblemon:power_herb"},
        {"Pokeball Artisan", "32024", "9", "cobblemon:net_ball"},
        {"Pokeball Specialist", "32025", "43", "cobblemon:net_ball"},
        {"Pokemon Pharmacist", "32026", "24", "cobblemon:hp_up"},
        {"Poketech", "32027", "7", "cobblemon:pokedex_red"},
        {"Poké Trader", "32028", "14", "cobblemon:poke_ball"},
        {"Pokémon Tech Specialist", "32029", "35", "rctmod:trainer_card"},
        {"Pot Trader", "32030", "7", "cobblemon:campfire_pot_green"},
        {"Potions Salesman", "32031", "56", "minecraft:blaze_powder"},
        {"Stone Specialist", "32032", "10", "cobblemon:fire_stone"},
        {"Supplement Specialist", "32033", "8", "cobblemon:x_attack"},
        {"Wilderness Trader", "32034", "29", "minecraft:leather"},
        {"X-Item Merchant", "32035", "8", "cobblemon:x_attack"}
    };
}
